In [8]:
import pandas as pd

baby_names = pd.read_csv("datasets/Popular_Baby_Names.csv")

In [9]:
bndf = baby_names[baby_names["Gender"] == "FEMALE"].groupby(["Year of Birth", "Child's First Name"]).sum()

df = bndf.rename_axis(index={"Year of Birth": "YOB", "Child's First Name":"Name"})


df

                                                         Gender  \
YOB  Name
2011 AALIYAH  FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...
     ABBY            FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALE
     ABIGAIL  FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...
     ADA             FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALE
     ADDISON  FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...
...                                                         ...
2021 Zissy                                               FEMALE
     Zoe                               FEMALEFEMALEFEMALEFEMALE
     Zoey                              FEMALEFEMALEFEMALEFEMALE
     Zoya                                                FEMALE
     Zuri                                          FEMALEFEMALE

                                                      Ethnicity  Count  Rank
YOB  Name
2011 AALIYAH  BLACK NON HISPANICHISPANICBLACK NON HISPANICHI...    924   245
     ABBY     HISPANICHISPANICHISPANICHISPANICHISPANICHISPAN...     70   546
     ABIGAIL  WHITE NON HISPANICASIAN AND PACIFIC ISLANDERBL...   1806   525
     ADA      ASIAN AND PACIFIC ISLANDERASIAN AND PACIFIC IS...     91   245
     ADDISON  WHITE NON HISPANICBLACK NON HISPANICBLACK NON ...    224   798
...                                                         ...    ...   ...
2021 Zissy                                   WHITE NON HISPANIC     31    59
     Zoe      HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...    195    77
     Zoey     HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...    107   143
     Zoya                            ASIAN AND PACIFIC ISLANDER     11    31
     Zuri                            HISPANICBLACK NON HISPANIC     49    70

[6980 rows x 4 columns]

In [10]:
df["My_Rank"] = df.groupby('YOB')['Count'].rank(ascending=False)

df[df["My_Rank"] == 1]

,,Gender,Ethnicity,Count,Rank,My_Rank
YOB,Name,,,,,
2011,ISABELLA,FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...,HISPANICWHITE NON HISPANICASIAN AND PACIFIC IS...,4151,252,1.0
2012,SOPHIA,FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...,ASIAN AND PACIBLACK NON HISPHISPANICWHITE NON ...,3773,288,1.0
2013,Sophia,FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...,ASIAN AND PACIFIC ISLANDERBLACK NON HISPANICHI...,3780,273,1.0
2014,Sophia,FEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMALEFEMA...,WHITE NON HISPANICBLACK NON HISPANICASIAN AND ...,3676,192,1.0
2015,Olivia,FEMALEFEMALEFEMALEFEMALE,HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...,589,22,1.0
2016,Olivia,FEMALEFEMALEFEMALEFEMALE,HISPANICWHITE NON HISPANICASIAN AND PACIFIC IS...,559,23,1.0
2017,Emma,FEMALEFEMALEFEMALEFEMALE,ASIAN AND PACIFIC ISLANDERBLACK NON HISPANICHI...,561,26,1.0
2018,Emma,FEMALEFEMALEFEMALEFEMALE,HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...,494,46,1.0
2019,Emma,FEMALEFEMALEFEMALEFEMALE,HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...,490,36,1.0
2020,Emma,FEMALEFEMALEFEMALEFEMALE,HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...,433,36,1.0
2021,Emma,FEMALEFEMALEFEMALEFEMALE,HISPANICASIAN AND PACIFIC ISLANDERWHITE NON HI...,426,39,1.0